FROM python:3.10-slim
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get install -y libpq-dev build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./extractload/requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./extractload/extractload.py /app/
COPY ./extractload/config.py /app/
COPY ./data_source /app/data_source


CMD ["python", "extractload.py"]
